default:
  image: docker:28-cli
  services:
    - docker:28-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  TAG:
    description: Tag for docker image
    value: latest

stages:
  - validate
  - format
  - build

lint-py:
  stage: validate
  tags:
    - bi
  image:
    name: cytopia/pylint
    entrypoint: ["/bin/ash", "-c"]
  script:
    - pylint ./*.py --rcfile=pylintrc --ignore=pylintrc | tee -a ./pylint_lint.log
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - pylint_lint.log
    expire_in: 1 week
  only:
    - master

format-black:
  stage: format
  tags:
    - bi
  needs: ["lint-py"]
  image:
    name: cytopia/black
    entrypoint: ["/bin/ash", "-c"]
  script:
    - python3 -m black --check --diff ./*.py | tee -a ./pyblack_lint.log
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - pyblack_lint.log
    expire_in: 1 week
  only:
    - master

build_job:
  tags:
    - bi
  stage: build
  image: google/cloud-sdk:alpine
  before_script:
    - echo "$GCP_SA_SECRET" | base64 -d > /root/sa.json
    - gcloud auth activate-service-account --key-file /root/sa.json
    - export GOOGLE_APPLICATION_CREDENTIALS="/root/sa.json"
    - gcloud auth configure-docker $GCP_ARTIFACT_REGISTRY_HOST
    - apk add --no-cache docker-cli
    - apk add --no-cache jq
    - TRIVY_LATEST_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r '.tag_name' | sed 's/v//g')
    - echo "Use Trivy version - $TRIVY_LATEST_VERSION"
    - wget https://github.com/aquasecurity/trivy/releases/download/v$TRIVY_LATEST_VERSION/trivy_${TRIVY_LATEST_VERSION}_Linux-64bit.tar.gz
    - tar xzvf trivy_${TRIVY_LATEST_VERSION}_Linux-64bit.tar.gz

  script:
    - docker build --tag $GCP_ARTIFACT_REGISTRY_HOST/$GCP_PROJECT_NAME/$ARTIFACT_REGISTRY_REPO/$CI_PROJECT_NAME:$TAG .
    - docker tag $GCP_ARTIFACT_REGISTRY_HOST/$GCP_PROJECT_NAME/$ARTIFACT_REGISTRY_REPO/$CI_PROJECT_NAME:$TAG  $GCP_ARTIFACT_REGISTRY_HOST/$GCP_PROJECT_NAME/$ARTIFACT_REGISTRY_REPO/$CI_PROJECT_NAME:$CI_COMMIT_TAG
    - ./trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db --no-progress --timeout 45m --output scanning-report.json $GCP_ARTIFACT_REGISTRY_HOST/$GCP_PROJECT_NAME/$ARTIFACT_REGISTRY_REPO/$CI_PROJECT_NAME:$TAG
    - ./trivy image --db-repository public.ecr.aws/aquasecurity/trivy-db --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db --ignore-unfixed --exit-code 1 --no-progress --timeout 45m --severity CRITICAL $GCP_ARTIFACT_REGISTRY_HOST/$GCP_PROJECT_NAME/$ARTIFACT_REGISTRY_REPO/$CI_PROJECT_NAME:$TAG
    - docker push $GCP_ARTIFACT_REGISTRY_HOST/$GCP_PROJECT_NAME/$ARTIFACT_REGISTRY_REPO/$CI_PROJECT_NAME:$TAG
    - docker push $GCP_ARTIFACT_REGISTRY_HOST/$GCP_PROJECT_NAME/$ARTIFACT_REGISTRY_REPO/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  artifacts:
    reports:
      container_scanning: scanning-report.json
  only:
    - tags
